### ISSUE TITLE
Home Assistant 2022.2.8  添加集成报错

### ISSUE THREAD

**Issue by yiqian987** [apgmer/hass-xiaodu#3]
版本：Home Assistant 2022.2.8
报错信息：

```
Logger: homeassistant.config_entries
Source: custom_components/hass-xiaodu/__init__.py:40
Integration: hass-xiaodu
First occurred: 16:17:28 (2 occurrences)
Last logged: 16:27:15

Error setting up entry XiaoDuCookie for xiaodu
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hass-xiaodu/__init__.py", line 40, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'
```

**Comment by linzhouzhou888** [comment]
我加了都正常   留个联系方式一起交流下
